


<CarouselExample>:
    direction:'right'
    # Adding 10 slides
        
    AsyncImage: 
        source:'images/c++.png' 
        allow_stretch:True

    AsyncImage: 
        source:'images/JavaScript_logo_2.svg.png' 
        allow_stretch:True
    AsyncImage: 
        source:'images/java.png' 
        allow_stretch:True
    AsyncImage: 
        source:'images/c#.png' 
        allow_stretch:True
    AsyncImage: 
        source:'images/python.png' 
        allow_stretch:True
        