BoxLayout:
    id: left_box
    canvas:
        Color:
            rgb: 0.6, 0.6, 0.6
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        size_hint_x: None
        width: left_box.width - right_box.width 
        text: "Hello Canvas"
        font_size: dp(40)       
    BoxLayout:
        width: 200
        id: right_box
        Button:
            text: 'I ma a button'